# Generated by Django 2.1.5 on 2019-06-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_step_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='TextStep',
        ),
    ]
