# Generated by Django 2.1.5 on 2019-06-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_truefalsequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
